### ISSUE TITLE
Icons not visible on GitHub pages site

### ISSUE THREAD

**Issue by ChristianMurphy** [cousquer/CardWebComponents#2]
On https://cousquer.github.io/CardWebComponents the icons are currently not visible.
![screenshot_2018-10-26 wip cardwebcomponent for uportal](https://user-images.githubusercontent.com/3107513/47573353-f8577800-d8f1-11e8-8d1f-0ee62f7d55a5.png)

The issue appears to be the same as https://github.com/uPortal-contrib/uPortal-web-components/issues/85
Where `@font-face` needs to be outside the shadow dom.

**Comment by cousquer** [comment]
Yes Good Catch @ChristianMurphy . Thanks

**Comment by cousquer** [comment]
@ChristianMurphy Could you check on your side if this issue is fixed?

**Comment by ChristianMurphy** [comment]
Looks good now, thanks @cousquer!
